services:
  postgres:
    image: postgres:16
    container_name: forgehub-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER: forgehub
      - POSTGRES_PASSWORD: forgehuc
      - POSTGRES_DB: forgehubdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: