export enum AuditAction {
    ORGANIZATION_CREATED = 'ORGANIZATION_CREATED',
    MEMBER_ADDED = 'MEMBER_ADDED',
    
    USER_REGISTERED = 'USER_REGISTERED',
    USER_LOGIN = 'USER_LOGIN',
    USER_VERIFIED = 'USER_VERIFIED',

    PROJECT_CREATED = 'PROJECT_CREATED',
    PROJECT_UPDATED = 'PROJECT_UPDATED',
    PROJECT_DELETED = 'PROJECT_DELETED',

    TASK_CREATED = 'TASK_CREATED',
    TASK_UPDATED = 'TASK_UPDATED',
    TASK_DELETED = 'TASK_DELETED',
    TASK_ASSIGNED = 'TASK_ASSIGNED',
    TASK_STATUS_CHANGED = 'TASK_STATUS_CHANGED'
};